Scrum 41 umziehen der anwendung auf die hitabis infrastruktur
DanielEdlich/masys-smart-schedular pull request #14
Opened 2024-12-30 11:26 UTC by calipee

https://masys-stundenplaner.atlassian.net/browse/SCRUM-41

2024-12-31 14:12 UTC, RemodifyBerlin requested changes
Hey, sieht soweit gut aus. Hast du es auch auf dem Server getestet? Funktioniert die Datenbankverbindung und Pipeline? Dann kann es auch gemerged werden.

2024-12-31 14:55 UTC, calipee commented
> Hey, sieht soweit gut aus. Hast du es auch auf dem Server getestet? Funktioniert die Datenbankverbindung und Pipeline? Dann kann es auch gemerged werden.

Pipeline funktioniert noch nicht aufgrund fehlender ENV @DanielEdlich und auf dem Server gibt es auch noch Probleme mit Traefik. 

+ Refresh funktioniert noch nicht wenn die Seite aktualisiert wird da Nextjs das irgendwie intern cached

2025-01-02 15:37 UTC, RemodifyBerlin commented
> > Hey, sieht soweit gut aus. Hast du es auch auf dem Server getestet? Funktioniert die Datenbankverbindung und Pipeline? Dann kann es auch gemerged werden.
> 
> Pipeline funktioniert noch nicht aufgrund fehlender ENV @DanielEdlich und auf dem Server gibt es auch noch Probleme mit Traefik.
> 
> * Refresh funktioniert noch nicht wenn die Seite aktualisiert wird da Nextjs das irgendwie intern cached

Danke! Teste es nochmal wenn die ENV gesetzt sind. Auto refresh sollte funktionieren bei der Implementierung, sowie local. Das sollte aufjedenfall getestet werden.

2025-01-05 19:57 UTC, RemodifyBerlin approved these changes

2025-01-05 20:07 UTC, merged